name: Bcakend CI/CD Pipeline Preview

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install dependencies
        run: |
            cd backend
            npm install

      - name: Run tests
        run: |
            cd backend
            npm test